package common;

public enum Action {
	GET_SUBSCRIBER("GET_SUBSCRIBER",0),
	UPDATE_SUBSCRIBER("UPDATE_SUBSCRIBER",1),
	LOGIN_USERNAME_PASSWORD("LOGIN_USERNAME_PASSWORD",2),
	LOGOUT_USER("LOGOUT_USER", 3),
	GET_MACHINES_LIST("GET_MACHINES_LIST",4),
	GET_AVAILABLE_PRODUCTS_IN_MACHINE("GET_PRODUCTS_IN_MACHINE_LIST", 5),
	GET_NOT_AVAILABLE_PRODUCTS_IN_MACHINE("GET_NOT_AVAILABLE_PRODUCTS_IN_MACHINE",6);
	private Action (final String mission,final int serialNumber ) {
	}
}
