package common;

public enum Response {
	FOUND_SUBSCRIBERS("FOUND_SUBSCRIBERS",0),
	DIDNT_FOUND_SUBSCRIBERS("DIDNT_FOUND_SUBSCRIBERS",1),
	UPDATE_SUBSCRIBERS_SUCCESS("UPDATE_SUBSCRIBERS_SUCCESS",2),
	UPDATE_SUBSCRIBERS_FAILD("UPDATE_SUBSCRIBERS_FAILD",3),
	WAIT_RESPONSE("WAIT_RESPONSE",4), 
	FAILED("FAILED",5), 
	ALREADY_LOGGED_IN("ALREADY_LOGGED_IN",6), 
	LOGGED_IN_SUCCESS("SUCCEED",7), 
	INCORRECT_VALUES("INCORRECT_VALUES",8),
	LOGGEDOUT_SUCCESSFULLY("LOGGEDOUT_SUCCESSFULLY", 9),
	FOUND_MACHINE_NAMES("FOUND_MACHINE_NAMES", 10),
	FOUND_MACHINES("FOUND_MACHINES",11),
	FOUND_PRODUCTS_FOR_DISPLAY("FOUND_PRODUCTS_FOR_DISPLAY", 12),
	FAILED_TO_GET_OFFERS("FAILED_TO_GET_OFFERS", 13),
	FOUND_OFFERS("FOUND_OFFERS",14),
	FAILED_TO_GET_ORDERS("FOUND_ORDERS",15),
	FOUND_ORDERS("FOUND_ORDERS",16),
	FOUND_CUR_STOCK("FOUND_CUR_STOCK", 17),
	FOUND_PAYMENT_DETAILS("FOUND_PAYMENT_DETAILS", 18),
	ORDER_PLACED_SUCCESSFULLY("ORDER_PLACED_SUCCESSFULLY", 19),
	REGISTER_CUSTOMER_TO_SUBSCRIBER_UNSUCCESSFULLY("REGISTER_CUSTOMER_TO_SUBSCRIBER_UNSUCCESSFULLY", 20),
	REGISTER_USER_TO_CUSTOMER_UNSUCCESSFULLY("REGISTER_USER_TO_CUSTOMER_UNSUCCESSFULLY", 21),
	REGISTER_USER_TO_CUSTOMER_SUCCESSFULLY("REGISTER_USER_TO_CUSTOMER_SUCCESSFULLY", 22),
	GET_CREDIT_CARD_BY_ID_UNSUCCESSFULLY("GET_CREDIT_CARD_BY_ID_UNSUCCESSFULLY", 23),
	GET_CREDIT_CARD_BY_ID_SUCCESSFULLY("GET_CREDIT_CARD_BY_ID_SUCCESSFULLY",24),
	APPROVE_REGISTER_REQUEST_UNSUCCESSFULLY("APPROVE_REGISTER_REQUEST_UNSUCCESSFULLY",25),
	APPROVE_REGISTER_REQUEST_SUCCESSFULLY("APPROVE_REGISTER_REQUEST_SUCCESSFULLY",26),
	FOUND_SUB_ID_LIST("FOUND_SUB_ID_LIST", 27);
	private Response(final String response,final int serialNumber) {
	}
}
