package common;

public enum Response {
	FOUND_SUBSCRIBERS("FOUND_SUBSCRIBERS",0),
	DIDNT_FOUND_SUBSCRIBERS("DIDNT_FOUND_SUBSCRIBERS",1),
	UPDATE_SUBSCRIBERS_SUCCESS("UPDATE_SUBSCRIBERS_SUCCESS",2),
	UPDATE_SUBSCRIBERS_FAILD("UPDATE_SUBSCRIBERS_FAILD",3),
	WAIT_RESPONSE("WAIT_RESPONSE",4), 
	FAILED("FAILED",5), 
	ALREADY_LOGGED_IN("ALREADY_LOGGED_IN",6), 
	LOGGED_IN_SUCCESS("SUCCEED",7), 
	INCORRECT_VALUES("INCORRECT_VALUES",8),
	LOGGEDOUT_SUCCESSFULLY("LOGGEDOUT_SUCCESSFULLY", 9),
	FAILED_TO_GET_OFFERS("FAILED_TO_GET_OFFERS", 10),
	FOUND_OFFERS("FOUND_OFFERS",11),
	FAILED_TO_GET_ORDERS("FOUND_ORDERS",12),
	FOUND_ORDERS("FOUND_ORDERS",13);
	private Response(final String response,final int serialNumber) {
	}
}
