package common;

public enum Response {
	FOUND_SUBSCRIBERS("FOUND_SUBSCRIBERS",0),
	DIDNT_FOUND_SUBSCRIBERS("DIDNT_FOUND_SUBSCRIBERS",1),
	UPDATE_SUBSCRIBERS_SUCCESS("UPDATE_SUBSCRIBERS_SUCCESS",2),
	UPDATE_SUBSCRIBERS_FAILD("UPDATE_SUBSCRIBERS_FAILD",3),
	WAIT_RESPONSE("WAIT_RESPONSE",4), 
	FAILED("FAILED",5), 
	LOGIN_USERNAME_PASSWORD("LOGIN_USERNAME_PASSWORD",6),
	ALREADY_LOGGED_IN("ALREADY_LOGGED_IN",7), 
	LOGGED_IN_SUCCESS("LOGGED_IN_SUCCESS",8), 
	INCORRECT_VALUES("INCORRECT_VALUES",9),
	LOGGEDOUT_SUCCESSFULLY("LOGGEDOUT_SUCCESSFULLY", 10),
	GETMACHINE_SUCCESSFULLY("GETMACHINE_SUCCESSFULLY", 11),
	GETMACHINE_UNSUCCESSFULLY("GETMACHINE_UNSUCCESSFULLY", 12),
	GETORDERREPORT_SUCCESSFULLY("GETORDERREPORT_SUCCESSFULLY", 13),
	GETORDERREPORT_UNSUCCESSFULLY("GETORDERREPORT_UNSUCCESSFULLY", 14),
	GETINVENTORYREPORT_SUCCESSFULLY("GETINVENTORYREPORT_SUCCESSFULLY", 15),
	GETINVENTORYREPORT_UNSUCCESSFULLY("GETINVENTORYREPORT_UNSUCCESSFULLY", 16);
	private Response(final String response,final int serialNumber) {
	}
}
